server:
  port: 8080

spring:
  application:
    name: spring-data-access-task

  datasource:
    url: jdbc:postgresql://localhost:5432/BOOK_TICKET_SERVICE
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml

  jpa:
    properties:
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
          use_query_cache: true
        generate_statistics: true